from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

from app.path_resolver import resolve_location, is_blocked_path
from app.session_memory import set_last_created_path
from app.ppt_agent.ppt_content_generator import generate_ppt_content
from app.ppt_agent.ppt_theme import (
    get_theme,
    set_slide_background,
    add_title,
    add_subtitle,
    add_footer,
    add_accent_bar,
    add_card
)


def get_unique_file_path(path: Path):
    if not path.exists():
        return path

    counter = 1

    while True:
        new_path = path.parent / f"{path.stem}_{counter}{path.suffix}"

        if not new_path.exists():
            return new_path

        counter += 1


def safe_filename(name: str):
    name = name.strip()

    if not name:
        name = "Orvix_Presentation"

    blocked_chars = ['<', '>', ':', '"', '/', '\\', '|', '?', '*']

    for char in blocked_chars:
        name = name.replace(char, "")

    name = "_".join(name.split())

    if not name.lower().endswith(".pptx"):
        name += ".pptx"

    return name


def add_bullet_slide(prs, slide_data, theme, slide_number):
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    set_slide_background(slide, theme["background"])
    add_accent_bar(slide, theme)

    title = slide_data.get("title", "Untitled Slide")
    bullets = slide_data.get("bullets", [])

    add_title(
        slide,
        title,
        theme,
        top=0.55,
        left=0.65,
        width=12,
        height=0.7,
        size=30
    )

    add_card(
        slide,
        left=0.85,
        top=1.65,
        width=11.6,
        height=4.85,
        theme=theme
    )

    bullet_box = slide.shapes.add_textbox(
        Inches(1.15),
        Inches(1.9),
        Inches(11.0),
        Inches(4.35)
    )

    frame = bullet_box.text_frame
    frame.clear()
    frame.word_wrap = True

    for index, bullet in enumerate(bullets[:5]):
        if index == 0:
            paragraph = frame.paragraphs[0]
        else:
            paragraph = frame.add_paragraph()

        paragraph.text = bullet
        paragraph.level = 0
        paragraph.font.size = Pt(21)
        paragraph.font.color.rgb = theme["text"]
        paragraph.space_after = Pt(12)

    add_footer(slide, "Generated by Orvix", theme, slide_number)

    return slide


def add_title_slide(prs, topic, theme, slide_data=None):
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    set_slide_background(slide, theme["background"])
    add_accent_bar(slide, theme)

    title = topic.title()

    if slide_data and slide_data.get("title"):
        title = slide_data.get("title")

    add_title(
        slide,
        title,
        theme,
        top=1.5,
        left=0.75,
        width=11.8,
        height=1.3,
        size=44
    )

    add_subtitle(
        slide,
        "A professional presentation generated by Orvix",
        theme,
        top=2.85,
        left=0.8,
        width=11.5,
        height=0.7,
        size=20
    )

    add_card(
        slide,
        left=0.85,
        top=4.15,
        width=5.7,
        height=1.25,
        theme=theme
    )

    info_box = slide.shapes.add_textbox(
        Inches(1.1),
        Inches(4.38),
        Inches(5.2),
        Inches(0.7)
    )

    frame = info_box.text_frame
    frame.clear()

    paragraph = frame.paragraphs[0]
    paragraph.text = "Clean • Structured • Presentation-ready"
    paragraph.font.size = Pt(18)
    paragraph.font.bold = True
    paragraph.font.color.rgb = theme["text"]

    add_footer(slide, "Generated by Orvix", theme, 1)

    return slide


def create_presentation(
    topic,
    filename,
    slide_count=6,
    location="desktop",
    user_command=None,
    open_after_create=True
):
    try:
        base_path = resolve_location(location)
        base_path.mkdir(parents=True, exist_ok=True)

        final_filename = safe_filename(filename)
        file_path = get_unique_file_path(base_path / final_filename)

        if is_blocked_path(file_path):
            return {
                "success": False,
                "message": f"Blocked for safety: {file_path}"
            }

        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        theme = get_theme(topic)

        slides = generate_ppt_content(
            topic=topic,
            slide_count=slide_count,
            user_command=user_command or ""
        )

        if not slides:
            slides = generate_ppt_content(
                topic=topic,
                slide_count=slide_count,
                user_command=""
            )

        add_title_slide(
            prs,
            topic,
            theme,
            slide_data=slides[0] if slides else None
        )

        content_slides = slides[1:] if len(slides) > 1 else slides

        current_slide_number = 2

        for slide_data in content_slides:
            if current_slide_number > slide_count:
                break

            add_bullet_slide(
                prs,
                slide_data,
                theme,
                current_slide_number
            )

            current_slide_number += 1

        prs.save(file_path)

        set_last_created_path(file_path)

        if open_after_create:
            try:
                from app.ppt_agent.ppt_opener import open_presentation
                open_presentation(file_path)
            except Exception:
                pass

        return {
            "success": True,
            "path": str(file_path),
            "message": f"PowerPoint created successfully: {file_path}"
        }

    except Exception as error:
        return {
            "success": False,
            "message": f"Failed to create PowerPoint: {error}"
        }