import json
import re
from unittest import result

from pymsgbox import prompt

try:
    from app.ai.providers import ask_ai
except Exception:
    ask_ai = None


def clean_text(text: str):
    if not text:
        return ""

    text = text.replace("**", "")
    text = text.replace("__", "")
    text = text.replace("`", "")
    text = re.sub(r"^#{1,6}\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def extract_json(text: str):
    if not text:
        return None

    text = text.strip()

    text = re.sub(r"^```json\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"^```\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    try:
        return json.loads(text)
    except Exception:
        pass

    match = re.search(r"\[[\s\S]*\]", text)

    if match:
        try:
            return json.loads(match.group(0))
        except Exception:
            return None

    return None


def make_slide(title, bullets):
    return {
        "title": clean_text(title),
        "bullets": [clean_text(item) for item in bullets if clean_text(item)]
    }


def fallback_slides(topic: str, slide_count: int = 6):
    topic_title = topic.strip().title()

    base = [
        make_slide(
            topic_title,
            [
                f"A clear overview of {topic_title}.",
                "Generated by Orvix for a clean presentation flow.",
                "Designed for simple explanation and professional delivery."
            ]
        ),
        make_slide(
            "Introduction",
            [
                f"{topic_title} is an important topic in modern technology and education.",
                "It helps people understand new ideas, systems, and real-world applications.",
                "This presentation explains the topic in a simple and structured way."
            ]
        ),
        make_slide(
            "Key Concepts",
            [
                "The topic includes basic ideas, practical methods, and useful applications.",
                "Understanding the core concepts makes the topic easier to apply.",
                "Each concept connects with real-life problems and solutions."
            ]
        ),
        make_slide(
            "Real-World Applications",
            [
                f"{topic_title} can be used in education, business, research, and daily life.",
                "It supports better decision-making and improves productivity.",
                "Many organizations use it to improve systems and services."
            ]
        ),
        make_slide(
            "Benefits and Challenges",
            [
                "Benefits include speed, accuracy, automation, and better organization.",
                "Challenges may include cost, privacy, technical skills, and reliability.",
                "A balanced approach is needed for successful use."
            ]
        ),
        make_slide(
            "Conclusion",
            [
                f"{topic_title} is useful, practical, and important for the future.",
                "It can solve real problems when used carefully and ethically.",
                "Learning this topic builds strong academic and professional value."
            ]
        ),
    ]

    if slide_count <= len(base):
        return base[:slide_count]

    extra_needed = slide_count - len(base)

    extra = []

    for index in range(extra_needed):
        extra.append(
            make_slide(
                f"Additional Insight {index + 1}",
                [
                    f"This slide adds more detail about {topic_title}.",
                    "It can be customized later with examples, diagrams, or data.",
                    "Orvix can improve this slide when AI quota is available."
                ]
            )
        )

    return base[:-1] + extra + [base[-1]]


def normalize_slides(slides, topic, slide_count):
    if not isinstance(slides, list):
        return fallback_slides(topic, slide_count)

    cleaned = []

    for slide in slides:
        if not isinstance(slide, dict):
            continue

        title = clean_text(slide.get("title", "Untitled Slide"))
        bullets = slide.get("bullets", [])

        if not isinstance(bullets, list):
            bullets = []

        bullets = [clean_text(str(item)) for item in bullets if clean_text(str(item))]

        if title and bullets:
            cleaned.append({
                "title": title,
                "bullets": bullets[:5]
            })

    if len(cleaned) < 3:
        return fallback_slides(topic, slide_count)

    return cleaned[:slide_count]


def generate_ppt_content(topic: str, slide_count: int = 6, user_command: str = ""):
    if ask_ai is None:
        print("PPT: ask_ai not available, using local fallback slides.")
        return fallback_slides(topic, slide_count)

    prompt = f"""
Return ONLY valid JSON.

Create content for a PowerPoint presentation.

User command:
{user_command}

Topic:
{topic}

Number of slides:
{slide_count}

Required JSON format:
[
  {{
    "title": "Slide Title",
    "bullets": [
      "Short bullet point 1",
      "Short bullet point 2",
      "Short bullet point 3"
    ]
  }}
]

Rules:
- JSON only.
- No markdown.
- No explanation.
- Exactly {slide_count} slides.
- Each slide should have 3 to 5 useful bullet points.
- Keep bullets short and presentation-friendly.
- Use simple English.
- Make content meaningful, not placeholder.
"""

    try:
        print("PPT: Trying AI provider...")

        try:
            result = ask_ai(prompt, use_cache=False)
        except TypeError:
            result = ask_ai(prompt)

        print("PPT AI RESULT:", result.get("success"))
        print("PPT AI ERROR:", result.get("error", ""))

        if not result.get("success"):
            print("PPT: AI failed, using local fallback slides.")
            return fallback_slides(topic, slide_count)

        slides = extract_json(result.get("response", ""))

        if slides is None:
            print("PPT: AI returned invalid JSON, using local fallback slides.")
            return fallback_slides(topic, slide_count)

        print("PPT: AI content generated successfully.")
        return normalize_slides(slides, topic, slide_count)

    except Exception as error:
        print("PPT: Exception occurred, using local fallback slides.")
        print("PPT ERROR:", error)
        return fallback_slides(topic, slide_count)