def to_component_name(feature_name: str):
    parts = feature_name.replace("-", "_").split("_")

    return "".join(
        part.capitalize()
        for part in parts
        if part.strip()
    )


def to_title(feature_name: str):
    return feature_name.replace("_", " ").replace("-", " ").title()


def generate_page_code(feature_name: str):
    component_name = to_component_name(feature_name)
    title = to_title(feature_name)

    return f'''function {component_name}() {{
  return (
    <section className="page">
      <h1>{title}</h1>
      <p>This page was generated by Orvix based on your project requirements.</p>
    </section>
  );
}}

export default {component_name};
'''


def generate_dynamic_feature_files(features):
    files = {}

    for feature in features:
        component_name = to_component_name(feature)

        if not component_name:
            continue

        file_path = f"src/pages/{component_name}.jsx"

        files[file_path] = generate_page_code(feature)

    return files