def generate_home_page(design_spec, project_name):
    industry = design_spec.get("industry", "Business")
    sections = design_spec.get("landing_sections", [])

    cards = ""

    for section in sections:
        cards += f"""
        <div className="card">
            <span className="badge">{industry.title()}</span>
            <h2>{section}</h2>
            <p>{section} section generated by Orvix AI.</p>
        </div>
        """

    return f"""
function Home() {{
  return (
    <div className="container page">

      <section className="hero">
        <span className="badge">Modern {industry.title()}</span>

        <h1>{project_name}</h1>

        <p>
          A professional {industry.title()} platform generated
          by Orvix according to your requirements.
        </p>

        <button>
          Get Started
        </button>
      </section>

      <div className="card-grid">
        {cards}
      </div>

    </div>
  );
}}

export default Home;
"""