PROJECT_TEMPLATES = {
    "python app": {
        "folders": ["app", "tests"],
        "files": {
            "app/__init__.py": "",
            "app/main.py": '''def main():
    print("Hello from Orvix Python App!")


if __name__ == "__main__":
    main()
''',
            "tests/test_main.py": '''def test_sample():
    assert True
''',
            "requirements.txt": "",
            "README.md": "# Python App\n\nGenerated by Orvix.\n\nRun:\npython app/main.py\n"
        }
    },

    "flask app": {
        "folders": [
            "app",
            "app/routes",
            "app/models",
            "app/templates",
            "app/static/css",
            "app/static/js",
            "tests"
        ],
        "files": {
            "app/__init__.py": '''from flask import Flask


def create_app():
    app = Flask(__name__)

    from app.routes.main_routes import main
    app.register_blueprint(main)

    return app
''',
            "app/routes/__init__.py": "",
            "app/routes/main_routes.py": '''from flask import Blueprint, render_template

main = Blueprint("main", __name__)


@main.route("/")
def home():
    return render_template("index.html")
''',
            "app/models/__init__.py": "",
            "app/templates/index.html": '''<!DOCTYPE html>
<html>
<head>
    <title>Flask App</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <h1>Welcome to your Orvix Flask App</h1>
    <script src="/static/js/script.js"></script>
</body>
</html>
''',
            "app/static/css/style.css": '''body {
    font-family: Arial, sans-serif;
    margin: 40px;
}
''',
            "app/static/js/script.js": 'console.log("Flask app generated by Orvix");\n',
            "run.py": '''from app import create_app

app = create_app()

if __name__ == "__main__":
    app.run(debug=True)
''',
            "requirements.txt": "flask\n",
            "README.md": "# Flask App\n\nGenerated by Orvix.\n\nSetup:\npip install -r requirements.txt\npython run.py\n"
        }
    },

    "django app": {
        "folders": [
            "config",
            "core",
            "templates",
            "static/css",
            "static/js",
            "media"
        ],
        "files": {
            "manage.py": '''import os
import sys


def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
    from django.core.management import execute_from_command_line
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
''',
            "config/__init__.py": "",
            "config/settings.py": '''from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "dev-secret-key"
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
''',
            "config/urls.py": '''from django.contrib import admin
from django.urls import path
from core.views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
]
''',
            "config/wsgi.py": '''import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
application = get_wsgi_application()
''',
            "core/__init__.py": "",
            "core/views.py": '''from django.shortcuts import render


def home(request):
    return render(request, "index.html")
''',
            "core/models.py": '''from django.db import models
''',
            "core/admin.py": '''from django.contrib import admin
''',
            "core/apps.py": '''from django.apps import AppConfig


class CoreConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "core"
''',
            "templates/index.html": '''<!DOCTYPE html>
<html>
<head>
    <title>Django App</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <h1>Django App Generated by Orvix</h1>
</body>
</html>
''',
            "static/css/style.css": '''body {
    font-family: Arial, sans-serif;
    margin: 40px;
}
''',
            "static/js/script.js": 'console.log("Django app generated by Orvix");\n',
            "requirements.txt": "django\n",
            "README.md": "# Django App\n\nGenerated by Orvix.\n\nRun:\npip install -r requirements.txt\npython manage.py runserver\n"
        }
    },

    "node express app": {
        "folders": [
            "src",
            "src/routes",
            "src/controllers",
            "src/models",
            "public"
        ],
        "files": {
            "package.json": '''{
  "scripts": {
    "start": "node src/server.js",
    "dev": "nodemon src/server.js"
  },
  "dependencies": {
    "express": "latest",
    "cors": "latest",
    "dotenv": "latest"
  },
  "devDependencies": {
    "nodemon": "latest"
  }
}
''',
            "src/server.js": '''const express = require("express");
const cors = require("cors");
require("dotenv").config();

const app = express();

app.use(cors());
app.use(express.json());

app.get("/", (req, res) => {
  res.json({ message: "Node Express App Generated by Orvix" });
});

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
''',
            ".env": "PORT=5000\n",
            "README.md": "# Node Express App\n\nGenerated by Orvix.\n\nRun:\nnpm install\nnpm run dev\n"
        }
    },

    "spring boot project": {
        "folders": [
            "src/main/java/com/orvix/app",
            "src/main/resources",
            "src/test/java/com/orvix/app"
        ],
        "files": {
            "pom.xml": '''<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.orvix</groupId>
    <artifactId>orvix-app</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>Orvix Spring Boot App</name>

    <properties>
        <java.version>17</java.version>
        <spring.boot.version>3.3.0</spring.boot.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring.boot.version}</version>
        </dependency>
    </dependencies>
</project>
''',
            "src/main/java/com/orvix/app/Application.java": '''package com.orvix.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
''',
            "src/main/java/com/orvix/app/HomeController.java": '''package com.orvix.app;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HomeController {
    @GetMapping("/")
    public String home() {
        return "Spring Boot Project Generated by Orvix";
    }
}
''',
            "src/main/resources/application.properties": "server.port=8080\n",
            "README.md": "# Spring Boot Project\n\nGenerated by Orvix.\n\nRun:\nmvn spring-boot:run\n"
        }
    },

    "ml project": {
        "folders": [
            "data/raw",
            "data/processed",
            "notebooks",
            "src",
            "models",
            "reports",
            "tests"
        ],
        "files": {
            "src/main.py": '''from train import train_model


def main():
    train_model()


if __name__ == "__main__":
    main()
''',
            "src/train.py": '''import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


def train_model():
    print("Load your dataset inside data/raw/")

    # Example:
    # df = pd.read_csv("../data/raw/data.csv")
    # X = df.drop("target", axis=1)
    # y = df["target"]
    # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    # model = RandomForestClassifier()
    # model.fit(X_train, y_train)
    # predictions = model.predict(X_test)
    # print("Accuracy:", accuracy_score(y_test, predictions))
''',
            "src/predict.py": '''def predict():
    print("Prediction module placeholder")
''',
            "requirements.txt": "pandas\nscikit-learn\nmatplotlib\nseaborn\njoblib\n",
            "README.md": "# Machine Learning Project\n\nGenerated by Orvix.\n\nFolders:\n- data/raw\n- data/processed\n- src\n- models\n- reports\n\nRun:\npip install -r requirements.txt\npython src/main.py\n"
        }
    },

    "data science project": {
        "folders": [
            "data/raw",
            "data/processed",
            "notebooks",
            "src",
            "models",
            "reports",
            "visualizations"
        ],
        "files": {
            "src/data_preprocessing.py": '''import pandas as pd


def clean_data(input_path, output_path):
    df = pd.read_csv(input_path)
    df = df.drop_duplicates()
    df.to_csv(output_path, index=False)
    print("Data cleaned successfully")
''',
            "src/model_training.py": '''def train():
    print("Model training placeholder")
''',
            "src/evaluation.py": '''def evaluate():
    print("Evaluation placeholder")
''',
            "requirements.txt": "pandas\nnumpy\nscikit-learn\nmatplotlib\nseaborn\n",
            "README.md": "# Data Science Project\n\nGenerated by Orvix.\n"
        }
    },

    "react app": {
        "folders": [
            "src",
            "src/components",
            "src/pages",
            "src/assets",
            "public"
        ],
        "files": {
            "package.json": '''{
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@vitejs/plugin-react": "latest",
    "vite": "latest",
    "react": "latest",
    "react-dom": "latest"
  },
  "devDependencies": {}
}
''',
            "index.html": '''<!doctype html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Orvix React App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
''',
            "src/main.jsx": '''import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./style.css";

createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
''',
            "src/App.jsx": '''function App() {
  return (
    <main className="app">
      <h1>React App Generated by Orvix</h1>
      <p>Your project is ready.</p>
    </main>
  );
}

export default App;
''',
            "src/style.css": '''body {
  margin: 0;
  font-family: Arial, sans-serif;
  background: #0f172a;
  color: white;
}

.app {
  min-height: 100vh;
  display: grid;
  place-items: center;
  text-align: center;
}
''',
            "README.md": "# React App\n\nGenerated by Orvix.\n\nRun:\nnpm install\nnpm run dev\n"
        }
    }
}