PROJECT_BLUEPRINTS = {
    "ecommerce": {
        "template": "react app",
        "folders": [
            "src/pages",
            "src/components",
            "src/data"
        ],
        "files": {
            "src/pages/Home.jsx": '''function Home() {
  return (
    <section>
      <h1>Welcome to Ecommerce Store</h1>
      <p>Discover products and shop easily.</p>
    </section>
  );
}

export default Home;
''',
            "src/pages/Products.jsx": '''import products from "../data/products";
import ProductCard from "../components/ProductCard";

function Products() {
  return (
    <section>
      <h1>Products</h1>
      <div className="grid">
        {products.map((product) => (
          <ProductCard key={product.id} product={product} />
        ))}
      </div>
    </section>
  );
}

export default Products;
''',
            "src/pages/Cart.jsx": '''function Cart() {
  return (
    <section>
      <h1>Shopping Cart</h1>
      <p>Your selected products will appear here.</p>
    </section>
  );
}

export default Cart;
''',
            "src/pages/Checkout.jsx": '''function Checkout() {
  return (
    <section>
      <h1>Checkout</h1>
      <p>Payment and delivery details will be handled here.</p>
    </section>
  );
}

export default Checkout;
''',
            "src/components/Navbar.jsx": '''function Navbar() {
  return (
    <nav className="navbar">
      <h2>Ecommerce</h2>
      <a href="#">Home</a>
      <a href="#">Products</a>
      <a href="#">Cart</a>
    </nav>
  );
}

export default Navbar;
''',
            "src/components/ProductCard.jsx": '''function ProductCard({ product }) {
  return (
    <div className="card">
      <h3>{product.name}</h3>
      <p>{product.price}</p>
      <button>Add to Cart</button>
    </div>
  );
}

export default ProductCard;
''',
            "src/components/Footer.jsx": '''function Footer() {
  return <footer>Generated by Orvix</footer>;
}

export default Footer;
''',
            "src/data/products.js": '''const products = [
  { id: 1, name: "Laptop", price: "$899" },
  { id: 2, name: "Headphones", price: "$99" },
  { id: 3, name: "Keyboard", price: "$49" }
];

export default products;
''',
            "src/App.jsx": '''import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Home from "./pages/Home";
import Products from "./pages/Products";
import Cart from "./pages/Cart";
import Checkout from "./pages/Checkout";
import "./style.css";

function App() {
  return (
    <>
      <Navbar />
      <main className="container">
        <Home />
        <Products />
        <Cart />
        <Checkout />
      </main>
      <Footer />
    </>
  );
}

export default App;
''',
            "src/style.css": '''body {
  margin: 0;
  font-family: Arial, sans-serif;
  background: #0f172a;
  color: white;
}

.navbar {
  display: flex;
  gap: 20px;
  align-items: center;
  padding: 16px 32px;
  background: #111827;
}

.navbar a {
  color: white;
  text-decoration: none;
}

.container {
  padding: 32px;
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 20px;
}

.card {
  background: #1e293b;
  padding: 20px;
  border-radius: 12px;
}

button {
  padding: 10px 16px;
  border: none;
  border-radius: 8px;
  cursor: pointer;
}
'''
        }
    }
}